### ISSUE TITLE
Login with GitHub and activated 2FA not possible

### ISSUE THREAD

**Issue by frudolph77** [phantomate/Untare#10]
I'm using my GitHub Account to log in into the official tandoor server. So I'd like to use this login in the aoo as well. 
But there is an popup with the error ` Instance of ApiConnectionException` and/or `Unable to login with provided credentials`

I've checked my credentials they are correct so it is a problem with the 2FA.

**Comment by phantomate** [comment]
Hi, yeah I never thought of that. I try to include this in the next release!

**Comment by phantomate** [comment]
Added better error message, I hope that helps
