### ISSUE TITLE
Meal plan: alternative title required 

### ISSUE THREAD

**Issue by syphernl** [phantomate/Untare#102]
### Bug Summary

In a recent update the alternative title when adding a recipe to a meal plan became required. Generally no alternative title is required making planning it a bit impractical.

### Reproduction Steps

- Add a recipe to the Meal plan
- Select a date
- see that it expects alternative title

### Expected Results

Alternative title should be optional

### Actual Results

Field needs to be filled

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by Mr-DblH** [comment]
I also think that would be great
