### ISSUE TITLE
Suggestion: Submit to f-droid

### ISSUE THREAD

**Issue by benneti** [phantomate/Untare#11]
Hey, thanks for the nice app!

Have you considered submitting the app on https://f-droid.org/ (assuming you don't use proprietary libraries and I think you would need to add a license)?

**Comment by phantomate** [comment]
Hi, I considered it yes, but I dont know how :D

**Comment by benneti** [comment]
I think the simplest is to create an issue with all the details of your app on https://gitlab.com/fdroid/rfp/-/issues and hope one of the more senior f-droid people packages it.

**Comment by gloriousDan** [comment]
An easier/ intermediate option could be to submit the app to the [IzzyOnDroid](https://gitlab.com/IzzyOnDroid/repo/) repository. It can take the app apk from the releases and has lesser inclusion criteria. Having it in the standard fdroid repository would be great nevertheless.

**Comment by Thovi98** [comment]
May I ping @Izzysoft ?

**Comment by IzzySoft** [comment]
PS: As the app does not declare any license, it's not eligible for a listing on either F-Droid or my repo, sorry.

**Comment by Thovi98** [comment]
> You can try. And what do you expect him to do? You could also try opening an [RFP](https://gitlab.com/fdroid/rfp/-/issues/) with F-Droid 😉

Will do, thanks for your reply and for the hint.

Hhmm, I didn’t see the lack of LICENSE, I will open an issue about it. Thanks!

**Comment by IzzySoft** [comment]
Thanks! I just edited your initial comment there so the bot can identify the correct repo. For picking a license, [this list](https://spdx.org/licenses/) might be helpful (while sticking with one approved by OSI/FSF).

**Comment by Thovi98** [comment]
@IzzySoft, there is now a license!
I've not yet had the time to try to understand how to integrate fastlane (I never did that), but maybe one day? 😅

**Comment by IzzySoft** [comment]
> there is now a license!

Cool! There is now [a listing](https://apt.izzysoft.de/packages/unofficial.tandoor.recipes/)… err, with the next sync around 7 pm UTC I mean :star_struck:

![image](https://github.com/phantomate/Untare/assets/6781438/2e4e6787-b0e7-4907-9b74-3d5cf632c2c6)

If one can point the app to a self-hosted instance, that `TetheredNet` will of course be dropped.

> I've not yet had the time to try to understand how to integrate fastlane (I never did that), but maybe one day?

Probably, yes. Maybe today. See below this comment, in a few minutes.

**Comment by FineFindus** [comment]
> If one can point the app to a self-hosted instance, that TetheredNet will of course be dropped.

I just installed the app and was able to point it to my self-hosted instance, so the anti-feature can be removed :)
