### ISSUE TITLE
Cannot log in - ApiConnectionException

### ISSUE THREAD

**Issue by bushwarp** [phantomate/Untare#15]
### Bug Summary

I installed the app from the Google Play Store on a Pixel 5 running Android 13. When I enter the URL and credentials for a self-hosted instance of Tandoor, I receive the error message "Instance of 'ApiConnectionException'". I have tried uninstalling and reinstalling the app but I get the same results.

### Reproduction Steps

1. Install Untare from Google Play Store
2. Enter URL for self-hosted instance
3. Enter login credentials and press login
4. Error: "Instance of 'ApiConnectionException'"
5. Fails to login

### Expected Results

Successful login.

### Actual Results

Failed login, error: "Instance of 'ApiConnectionException'"

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by phantomate** [comment]
Hi bushwarp, which tandoor recipes version are you using? Please update to the latest version

**Comment by bushwarp** [comment]
Hi, I updated tandoor and am having the same issue with version 1.4.6.

**Comment by phantomate** [comment]
Hm thats strange, do you use 2FA or something like that? Does your login work on your selfhosted website?

**Comment by bushwarp** [comment]
Not using 2FA and I can log in just fine from a browser. Could it possibly be a firewall issue?

**Comment by Tchiimy** [comment]
> Not using 2FA and I can log in just fine from a browser. Could it possibly be a firewall issue?

Hi, I'm hosting tandoor on my RPi4 and I have the same problem with the "ApiConnectionException" on this app.

My adress to access tandoor is not https but http, could it be something linked with unstrusted certificate (in general I have to validate an option that says "trust this certificate anyway" in other selfhosted apps that I try to connect to my android.

**Comment by phantomate** [comment]
The app directly connects via API to your tandoor instance, there is no firewall inbetween. Do you use any kind of language special characters for you password? Maybe there is an issue with escaping the characters. Other question is, if you use http or https as url?

**Comment by bushwarp** [comment]
I changed my password to one with no special characters and got the same result. I have tried both http and https, neither work. The tandoor instance is behind a reverse proxy which automatically redirects http to https.

**Comment by phantomate** [comment]
Hm, you have the same setup as I do. Did you specify https when providing the URL in the app? I tried without and got the same error. If you didn't tried already, prefix your URL with https:// and remove www

**Comment by fg64** [comment]
Wanted to chime in on this issue.  I have a self hosted Tandoor Recipes.  It is running behind a Cloudflare tunnel.  I can access Tandoor away from home on a laptop and from my phone through a browser and all works fine.  When I attempt to log in through the app I get the following error "User api error - wrong credentials"  The same credentials are used in a browser and logs in with no issue.  I did specify https:// in the app.  Any suggestions are appreciated.

**Comment by phantomate** [comment]
@bushwarp did it work? ApiConnectionException means that it's not possible to connect to the API. This is due to a faulty URL.

@fg64 For you the URL is correct and you can connect to the API. Unfortunately the API is responsing with an error. Due to the missing error documentation on tandoor recipes the app assumes that this is a wrong credentials error (which it is most of the time, never saw a different error on my side). What you could do is, use i.e. Postman and try the API call manually and check what error do you receive. Sorry that I can't help there any more.

**Comment by fg64** [comment]
Thank you for the reply.  I'll play around with that next week.

**Comment by bushwarp** [comment]
Still receiving the same error message. I am specifying https:// and I have double checked the URL and the credentials. Everything works just fine in my browser but not in the app.

**Comment by phantomate** [comment]
@bushwarp did you also try to do the login with postman? There you can track errors better and see what is causing these issues
