### ISSUE TITLE
Automatic change of the theme (dark / light)

### ISSUE THREAD

**Issue by update-freak** [phantomate/Untare#18]
### Your Request

Hello developer,

it would be great to have to automatic change of the theme (dark / light) according to the system theme.
For me the light design makes sense when I cook at midday, but the dark design is better when I cook in the evening.
Currently I have to manually select the theme. An automatic selection would be very helpful.

### The Current State

manual change of the theme

**Comment by phantomate** [comment]
Hi @update-freak , the app is already able to detect the system theme setting. Is you system theme capable of switching at day and night time?

**Comment by update-freak** [comment]
Ah ok. I only found an option to select light or dark. I will test the android app if it switches to dark at the evening.

**Comment by phantomate** [comment]
Hi @update-freak I had a look and I cache the theme setting. I could disable that as long as you don't manually switch the theme in the settings

**Comment by update-freak** [comment]
Hi @phantomate How to set then the automatic mode when I already changed to dark or light. Maybe you can intruduce here a setting automatic?

**Comment by phantomate** [comment]
@update-freak I will include this in the next update
