### ISSUE TITLE
Indication of portions from meal plan incorrect

### ISSUE THREAD

**Issue by pxlfrk** [phantomate/Untare#20]
### Bug Summary

In the Tandoor web UI, when I add a recipe to the meal plan, I can select the number of servings. This is also read and displayed correctly online when I view the recipe there in the meal plan view. In the app, it always shows the default number of servings for the recipe in the meal plan.

### Reproduction Steps

Add recipe with e.g. servings = 10 to menu plan.
Open the menu and compare the portion number online with the app.

### Expected Results

The portions should be taken correctly from the meal plan.

### Actual Results

The portion count is always (as far as I could tell) pulled from the default portion count in the actual recipe.

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by pxlfrk** [comment]
Hi @phantomate - yeah, for sure i'll clarify. 

Usually, i am planning our weekly meal plan on the computer in the tandoor web ui. When we have guests for example i'll increase the portion counter on a meal in the meal plan to 4 or 6, when we are alone i'll stay at lets say two. When cooking the meals in the kitchen i regulary use the untare mobile app - and refer to the portion count shown in the meal plan there. While creating the screenshots i noticed that when you long-press the recipe and edit the recipe in the meal-plan, you get displayed the "correct" portion count. Howver - just for convenience - it would be great if this information could also be displayed in the recipe view next to the portion switches.

_Therefore this shoule be classified as improvement rarer than a real bug._

**Tandoor-Web-UI:**
Add recipe to meal plan with 6 portions
![image](https://user-images.githubusercontent.com/39946364/228902647-cfccc604-fdeb-40b1-9a62-ab1cfdddffa2.png)

**View Recipe in meal Plan (Web-UI):**
![image](https://user-images.githubusercontent.com/39946364/228903084-b9204c7b-5c07-41ef-bcb4-4229d932c4aa.png)

**Untare View Meal-Plan Edit-View:**
![Screenshot_2023-03-30-18-31-33-27_20fae100620cda206715c5ad77a93828](https://user-images.githubusercontent.com/39946364/228904975-b08969be-6414-4be0-a0e9-9bf99f259c01.jpg)

**Untare Recipe View:**
![image](https://user-images.githubusercontent.com/39946364/228904923-7319ce6e-51a4-4100-b0a0-9d4e75477714.png)


Un

**Comment by phantomate** [comment]
@pxlfrk thanks for clarifying. The question about displaying the information of the meal plan on the recipe detail page is, how to determine what is displayed. Should it be future mealplan entries or also the one in the past? What about if you have the same recipe last week and this week, what should be displayed. Further, what if you have the recipe two times in a week, which information should be taken. 
And additionally, should this just be a text for information purpose?

**Comment by phantomate** [comment]
Do you have some suggetions? If not, I close this issue

**Comment by phantomate** [comment]
Closed due to inactivity
