### ISSUE TITLE
Landscape mode doesn't work on Android 

### ISSUE THREAD

**Issue by blknight88** [phantomate/Untare#25]
Even in the latest update that just came out landscape mode still does not work.

**Comment by phantomate** [comment]
That's correct, because I deactivated it. Why should there be a landscape mode? What are the advantages?

**Comment by blknight88** [comment]
Why deactivate it and remove the user the choice? In my opinion, if you don't like landscape mode, then just disable auto rotate in the OS rather restrict the app from having that ability. There are also 3rd party apps that can give you per app control of rotation settings.

As for the use case, my wife uses a tablet for viewing recipes when she cooks and she has a mount under our cabinets to hold the tablet which only works in landscape mode. I could possibly get a mount that would work in portrait mode but that would make the tablet take up valuable cooking space which is why she has one that is for landscape mode.

**Comment by phantomate** [comment]
Added support
