### ISSUE TITLE
Offline mode for recipes

### ISSUE THREAD

**Issue by Friendly-Banana** [phantomate/Untare#28]
### Your Request

When the server is not reachable, the recipes should still be available.
There could be UI to select the individual recipes that should be stored for offline usage or simply one button to mass-download all recipes.

### The Current State

Versions 1.0.0 and 0.1.0  try to get the newest recipes from the server and, if that fails, show the cached recipes. The current version 1.1.1 only shows the loading icon, making the recipes not accessible.
Maybe using a timeout to then fallback on the cache is possible?

**Comment by phantomate** [comment]
Hi @Friendly-Banana, yes I deactivated the caching, because it was buggy and sometimes not all recipes were loaded

**Comment by phantomate** [comment]
Added cache back to the recipe list, after a timeout of 10 seconds

**Comment by Friendly-Banana** [comment]
Great, thanks. 
Is there an easier way to add things into the cache (and keep them there) than clicking each recipe?

**Comment by phantomate** [comment]
Unfortunately not. The recipe list we receive from the api doesnÄt have all of the recipe data. Therefore you need to open every recipe to fetch all data (i.e. instructions, ingredients etc.) and store it in the cache
