### ISSUE TITLE
Drop down list not clickable after 1.1.0 update

### ISSUE THREAD

**Issue by panoskpv** [phantomate/Untare#30]
### Bug Summary

I have crdroid 9(android 13) vanilla with microg. I cannot use drop down lists at the app after 1.1.0. List is visible but when tapping on it is like tapping on whatever is on the back. Same does not happen in Samsung phone with  android 12.

### Reproduction Steps

As per above.

### Expected Results

Be able to tap on drop down list

### Actual Results

Tapping not working

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by phantomate** [comment]
Hi, sorry to hear that. Unfortunately I can't help you. It's working finde on different android versions and android phones and also in ios. I can just suggest using something different than crdroid or search if other crdroid user also have problems with dropdowns in apps

**Comment by panoskpv** [comment]
This is the only all that i have this problem... Have you confirmed that other android 13 devises are working as supposed?

**Comment by phantomate** [comment]
Yes, I have 3 android phones here and on all it works. I also use CalyxOS and there it works flawlessly. I had a look on my PlayStore statistics and over 300 people using android 13 without reporting a bug. Sorry but I can't reproduce the error and I don't see other people having probems
