### ISSUE TITLE
Login does not work with self signed certificate

### ISSUE THREAD

**Issue by wolflu05** [phantomate/Untare#31]
### Bug Summary

If I try to connect to a server using a self signed certificate Login fails with error: `Instance of 'ApiConnectionException'`. Generally it would be good to have some better error messages here to see what's wrong:
- Cannot connect to server
- User or password invalid
- cannot verify ssl cert
- ...

![image](https://github.com/phantomate/Untare/assets/76838159/8775eaf6-25da-45da-8c1b-143664dedb9f)

(I made sure that this is actually related to my self signed certificate by disabling the force of https redirect which shows that it works then.)

### Reproduction Steps

1. Set up an tandoor server with an reverse proxy that uses a self signed certificate.
2. Try to login in the iOS app
3. See error

### Expected Results

Login should work and I should be able to browse the recipes normally. Maybe it's a good idea to add a use strict https checking setting instead of ignoring it every time.

### Actual Results

I get an Error.

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by phantomate** [comment]
Added better error message, I hope that helps

**Comment by wolflu05** [comment]
@phantomate Thank you for implementing that, but that is not the main scope of this issue. I opened this issue because I cannot connect to a server using a self signed certificate. Better error messages would just help to identify the problem but not fix it. We need some way to ignore self signed certificates.

**Comment by phantomate** [comment]
Hi @wolflu05, thats right but at this point we don't know if it's an issue with the app or the server setup. The error messages could help to identify that. If it's app related please provide me the error message and I open this issue again

**Comment by wolflu05** [comment]
Sure, I'll do once it's available on ios, hopefully this happens quicker this time than on the initial publish where apple rejected it. 
But I think there are some adjustments needed, because other servers using an official certificate work with https. Disabling the force ssl option on my reverse proxy also works, but I don't want to use http only. Using the [inventree-app](https://github.com/inventree/inventree-app) (also an OSS flutter app) works also behind the same reverse proxy having force ssl enabled, because this app has an extra switch to ignore strict ssl cert checking.

**Comment by phantomate** [comment]
The new version is already available on iOS. That was fast :D
Hm thats strange, I use nginx proxy manager as reverse proxy, also together with force SSL and everything is working fine.

**Comment by wolflu05** [comment]
That was fast :D - but as I assumed, this does not work. The specific error now is: 
```
HandshakeException: Handshake error in client (OS Error: CERTIFICATE_VERIFY_FAILED: application verification failure (handshake.cc:393))
```

The issue is that you certificate might be signed by a trusted CA, mine not. Unfortunately I'm not familiar with flutter so I have no idea how to fix this, but googeling returned some promising [SO discussions](https://stackoverflow.com/questions/54285172/how-to-solve-flutter-certificate-verify-failed-error-while-performing-a-post-req), maybe they help you.

I followed this guide from [christian lempa](https://github.com/ChristianLempa/cheat-sheets/blob/main/misc/ssl-certs.md), but if you want to test this locally, [mkcert](https://github.com/FiloSottile/mkcert) should work pretty easy to generate certificates which you can import via nginx-proxy-manager.

<img width="501" alt="image" src="https://github.com/phantomate/Untare/assets/76838159/b4257d2c-f7e1-4a38-98e8-b336f94498b3">
