### ISSUE TITLE
Cannot enter server url on iOS

### ISSUE THREAD

**Issue by wolflu05** [phantomate/Untare#32]
### Bug Summary

I cannot directly enter the server url in the iOS app because there are no `:`, `/` or `.` chars available on the displayed keyboard that are needed for a url. (The part of the url that you already see in the video was copied from another textfield in to field using the clipboard).

https://github.com/phantomate/Untare/assets/76838159/0d58e157-b928-4b15-a249-234f0509740e

(This video shows how I tried both keyboards (German/English) and also their numpad, but I cannot input the required chars)

### Reproduction Steps

1. Open iOS app
2. Try to login with a server by entering the url
3. See the shown keyboards that do not offer a `.`, `/` neither a `:`

### Expected Results

Keyboard should be a normal keyboard. (I think there is actually a special keyboard type for URLs)

### Actual Results

Keyboard is a (alpha-)numeric keyboard only. 

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by phantomate** [comment]
Hi, yes I also discovered this issue when I released the app. I had no time until now to look into it. It will be fixed in the next release

**Comment by phantomate** [comment]
Fixed
