### ISSUE TITLE
Filter by Keyword

### ISSUE THREAD

**Issue by rinosaur681** [phantomate/Untare#33]
### Your Request

This might already be present and I've somehow missed it but currently I don't think its possible to filter by keyword (tags) in the app like it is in the web app. 

Ideally there would be an option to filter by keyword either when searching or by tapping the keyword currently shown on the recipe page

**Comment by phantomate** [comment]
Good idea, I try to implement it

**Comment by phantomate** [comment]
I did some investigations and in my opinion there is no need for it. You can use the normal search in the app du accomplish this. You just have to adjust your search settings in the web app to include keywords
