### ISSUE TITLE
Error With Fractions

### ISSUE THREAD

**Issue by royaltongue** [phantomate/Untare#35]
### Bug Summary

When adding ingredients in Tandoor, you can't put fractions directly, like `2/3 cups`. Instead. I put `0.66 cups`, which is then converted to a fraction when viewing the recipe, like shown here: ![image](https://github.com/phantomate/Untare/assets/61848270/1df3c00e-7ae8-49cd-acaf-a30d84d0b09d)

However. when viewing the recipe in Untare, the fraction is show as `33/50 cups`, which isn't wrong technically, but also isn't very helpful:
![image](https://github.com/phantomate/Untare/assets/61848270/9a9fa7ac-1590-4c85-b777-a73c35f9c66e)

### Reproduction Steps

Create a recipe with an ingredient measured in a fraction and view it within Untare

### Expected Results

Expected result is to show `2/3 cups` instead of `33/50 cups`

### Actual Results

Ingredient is measured as `33/50 cups`

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by phantomate** [comment]
Hi, thats realy a bit inconvenient, I try to change it in the next update

**Comment by phantomate** [comment]
Corrected the calculation
