### ISSUE TITLE
 Recipes in recipes just go poof in the app

### ISSUE THREAD

**Issue by TheDeluxeThrowaway** [phantomate/Untare#36]
### Bug Summary

![Screenshot_20230627_130011](https://github.com/phantomate/Untare/assets/134332457/812e6fff-324d-4a27-81c4-dcfc4b6adc86)
![image](https://github.com/phantomate/Untare/assets/134332457/a9ec9d89-7da3-4759-99ff-0c1531d72a90)
 recipes 
 
 Recipes in recipes just go poof in the app

### Reproduction Steps

Recipes in recipes

### Expected Results

Recipes in recipes no poof in the app

### Actual Results

 Recipes in recipes just go poof in the app

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by phantomate** [comment]
Recipes in recipes is not supported yet but it will be in future updates

**Comment by TheDeluxeThrowaway** [comment]
@phantomate Any idea when we can get line breaks between multiple steps? 
![image](https://github.com/phantomate/Untare/assets/134332457/b8e68b98-1eed-41b9-aa85-b2e593767f1e)
![image](https://github.com/phantomate/Untare/assets/134332457/26ecc983-81a8-4e7f-8ea7-8b0183376ba3)
