### ISSUE TITLE
dependecies broken

### ISSUE THREAD

**Issue by MeisterBob** [phantomate/Untare#38]
### Bug Summary

I tried to build the app on the actual stable flutter 3.10.6 and it fails to solve the dependencies
```
> flutter pub get
Resolving dependencies... (1.0s)
Because untare depends on
  flutter_localizations from sdk which depends
  on intl 0.18.0, intl 0.18.0 is required.
So, because untare depends on intl ^0.17.0,
  version solving failed.
```

### Reproduction Steps

checkout main (e9209d1acfbd766d300f627686dfdddf525daaba)
```
flutter channel stable
flutter upgrade
flutter pub get
```

### Expected Results

dependencies are getting installed and we can continue with the actual build.

### Actual Results

dependencies solving fails.

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by phantomate** [comment]
I'm using 3.7.12, try it with that version

**Comment by MeisterBob** [comment]
Thank you, working fine with 3.7.12.
