### ISSUE TITLE
Ingredients and Preparations not visible

### ISSUE THREAD

**Issue by ccarpo** [phantomate/Untare#45]
### Bug Summary

In my Xiaomi Poco X4 5G with MIUI 13 and 14 the ingredients and the preparations are Not visible in a receipe.
The information are visible in the website.
It happens in normal and dark mode.

![Screenshot_2023-08-10-22-42-05-698_unofficial tandoor recipes](https://github.com/phantomate/Untare/assets/273212/a6b2f2fe-c266-44c0-ae62-d62544d6994b)

### Reproduction Steps

Happens for every receipe I open.

### Expected Results

Visible ingredients and preparation steps

### Actual Results

Only a grey area visible.

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by fabjoe91** [comment]
Same on iOS devices. Can reproduce this bug.

**Comment by phantomate** [comment]
Oh thats strange. Did it work on previous versions? Does a fresh install helps?

**Comment by ccarpo** [comment]
K. I installed it twice, over the PlayStore before opening the issue and it had no effect. 

Now I installed 1.0.0 from GitHub and the problem vanished. I upgraded to 1.1.0, 1.1.1 and 1.1.2 and it kept working. 

Then I uninstalled and reinstalled from PlayStore and it kept working. 

For me it looks like a communication issue (because now I geht a loading circle in the ingredients view) which was in the somehow cached in the persisted data. 

If you do not want to investigate further we can close the issue from my side.

**Comment by fabjoe91** [comment]
Strange, now it works for me too. Nothing changed.

**Comment by ccarpo** [comment]
Maybe it was backend related?

**Comment by fabjoe91** [comment]
Possible, cause I’m new in the game. It’s my first try using tandoor (and the app). 
But why was the recipes loading, but not the details? 🙈 will never now.

**Comment by phantomate** [comment]
@ccarpo I think it's hard to reproduce. But I don't think that this is backend related except you disabled your wifi and mobile data. But this would only cause ingredients and steps not loading but not the buggy theme.

**Comment by phantomate** [comment]
@fabjoe91 That are two api calls, one to load a list of recipes and an other to load all ingredients and steps. So as I said above, if you don't have a internet connection, the ingredients and steps won't load. But this is not the explaination for the buggy theme

**Comment by ccarpo** [comment]
I think either the second API call was not triggered because the ui component didnt't load at all or it was triggered but did not return useful data.
But as you say it is hard to reproduce now. 
If I encounter it again I'll do some experiments and post my findings.

**Comment by phantomate** [comment]
Thank you!
