### ISSUE TITLE
Untare deletes existing supermarket category

### ISSUE THREAD

**Issue by rsrmean** [phantomate/Untare#46]
### Bug Summary

When adding a food to the shopping list, Untare removes its supermarket category.

### Reproduction Steps

- Assign category to food

![Screenshot_20230812-092135_1](https://github.com/phantomate/Untare/assets/87638107/958cd220-5039-4b2e-bfc6-1f79176214c3)

- Add food to shopping list in Untare - category gone

![Screenshot_20230812-092203_1](https://github.com/phantomate/Untare/assets/87638107/c3e16709-4ef1-4d64-957f-6ca536d37382)

- Confirm category removal in Tandoor UI

![Screenshot_20230812-092220_1](https://github.com/phantomate/Untare/assets/87638107/4fc9980c-86b7-44b1-9830-e50a3f054fcf)

### Expected Results

The category should be retained. 

### Actual Results

The category is deleted from the food.

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by phantomate** [comment]
You are right, I try to fix that in the next release
