### ISSUE TITLE
Drag ingredient and scroll

### ISSUE THREAD

**Issue by languagemaniac** [phantomate/Untare#47]
### Your Request

Hi, just installed tandoor and immediately installed this app.

When I import a recipe from a website I see that you can drag ingredients to different steps, although if you have a big list of ingredients, and you want to drag one ingredient say from step 1 to step 5, you have to go dragging it from step 1 to step 2, then scroll, then drag again from step 2 to step 3, etc.

It would be nice if you could scroll while dragging and just drop it where it belongs.

**Comment by languagemaniac** [comment]
> Hi @languagemaniac it is possible. The way I do this is to hold the ingredient with my right thumb and scroll with my left thumb on the other side. Please try this out

Hi, I tried but it doesn't scroll. Maybe it's because I have edge gestures enabled (I swipe from the edges to change screens, go back, etc).

**Comment by languagemaniac** [comment]
> Hi @languagemaniac it is possible. The way I do this is to hold the ingredient with my right thumb and scroll with my left thumb on the other side. Please try this out

Got it, it does work. Though it would be nice if it could be done with just the index finger, by dragging from the center of the screen. Thanks

**Comment by phantomate** [comment]
Sorry it's not planned to implement anything like that, because the current solution is working
