### ISSUE TITLE
Include URL for imported recipes 

### ISSUE THREAD

**Issue by samriggio** [phantomate/Untare#49]
### Your Request

Include the source URL for recipes imported from websites. The Tandoor web interface shows the URL at the bottom of the recipe page, but it could also be included in the "3 dots" menu.

It can be useful to access the source if something wasn't imported correctly or to view recipe comments, notes, etc, and for sharing to someone without Tandoor access.

**Comment by phantomate** [comment]
Hi, that's a good idea. I try to implement it in the next release
