### ISSUE TITLE
Add filter option for recipies

### ISSUE THREAD

**Issue by update-freak** [phantomate/Untare#53]
### Your Request

I use categories (with the tag (Schlüsselwort in german) feature) to organise my recipies by "use case", e.g. Lunch, Party, Breakfast.
Therefore it would be great I could also filter in the receipies tab in the app, e.g. for lunch -> that all the pary or breakfast receipies are hidden.

![2023-10-09 19_41_01-Stichwörter](https://github.com/phantomate/Untare/assets/40196995/d8b08efa-8bf3-461f-8737-54be26bdab9c)
![2023-10-09 19_41_25-Suchen](https://github.com/phantomate/Untare/assets/40196995/f8b52cc3-4768-4e5e-b850-a31456872a04)

### The Current State

Currently no option to hide receipies

**Comment by phantomate** [comment]
Hi, your can adjust the search option in your tandoor server settings. There you can enable searching for tags and more

**Comment by update-freak** [comment]
can you please post a screenshot how to enable searching for tags or describe it more in detail.
I checked it in the settings but did not found the option with tags.

**Comment by phantomate** [comment]
Yes, open Admin settings -> Search preferences -> choose a user -> Add tags for the searches you want
You even can add ingredients and more

**Comment by update-freak** [comment]
thanks a lot.
Ticket can be closed,
