### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by Thovi98** [phantomate/Untare#54]
### Bug Summary

As of now, no LICENSE file is created, which has several legal implications and does not meet de requirements for F-Droid.

See https://github.com/phantomate/Untare/issues/11.

### Reproduction Steps

Look at the code.

### Expected Results

To have a LICENSE file.

### Actual Results

No LICENSE file.

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by phantomate** [comment]
Hi, 
I added a license.

a29a47b2f397b8dd229776908eb079254522238b

**Comment by Thovi98** [comment]
Thank you! :D
