### ISSUE TITLE
Change space

### ISSUE THREAD

**Issue by languagemaniac** [phantomate/Untare#55]
### Your Request

I have two spaces, can't change space through the app, it just displays whatever space is selected in the server.

Please make it possible to change space, thanks

**Comment by phantomate** [comment]
Hi, there is currently no API endpoint for switching spaces. That's why I just list them

**Comment by languagemaniac** [comment]
> Hi, there is currently no API endpoint for switching spaces. That's why I just list them

Oh, i see. Closing this then
