### ISSUE TITLE
Meal plan api error - could not create meal plan

### ISSUE THREAD

**Issue by theflyer08** [phantomate/Untare#56]
### Bug Summary

In Android & iOS App untare following error occurs adding a recipe to the mean plan: meal plan api error - could not create meal plan (error 2).
Furthermore, there is an error message opening the app: type "Null" is not a subtype of type 'string' in type case (error 1).
The error should be associated with the new tandoor version, since untare was not updated on Android and iOS today, while this image has been installed on docker today: vabene1111/recipes:latest

Thank you for your help.

### Reproduction Steps

1. Open android or ios app
2. add a recipe to the meal plan

### Expected Results

1. no error message. 
2. added recipe to meal plan

### Actual Results

1. error message: type "Null" is not a subtype of type 'string' in type case
2.  error message: meal plan api error - could not create meal plan

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by phantomate** [comment]
You are right, after the update I get the same error. I need to investigate what changed on the api level. Unfortuately it's almoast holiday season and I don't know, if I can deploy an update this year. 
For now please downgrade your version

**Comment by theflyer08** [comment]
Thank you for the new release. Works perfect.
