### ISSUE TITLE
User API Error, could not fetch data

### ISSUE THREAD

**Issue by m4tz3** [phantomate/Untare#57]
### Bug Summary

I don't know what i'm doing wrong.
Password and Username are correct.

### Reproduction Steps

Trying to Login with untare.

### Expected Results

Logged in

### Actual Results

Error message
![1000007911](https://github.com/phantomate/Untare/assets/6939489/79d2eab6-dd3c-4573-84d8-8d00030bfdf6)

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by phantomate** [comment]
Hi Matze, the good thing is that you are already logged in. So you have connection to your instance. The issue here is, that right after the login the app tries to fetch the users. And that's where the call fails. 

Are you able to call the /api/user/ endpoint with the API browser on the web version or with something like postman?

**Comment by langerdennis** [comment]
I am facing the same issue recently - has worked in the past. I had not updated my Docker image of Tandoor, must have happened with an app release. At first meal plan and shopping list did not work anymore, then I deleted app storage and now I cannot log in anymore. API calls via browser endpoint work. I have now updated the Docker image as well, but did not help.

**Comment by phantomate** [comment]
@langerdennis Do you have the same error like m4tz3 - could not fecth user data? Or is it a different api error?

**Comment by langerdennis** [comment]
@phantomate Yes, now same error.

**Comment by phantomate** [comment]
Are you able to login into the official server with the demo/demo user? Is it working there?

**Comment by langerdennis** [comment]
Yes, just tried and that actually works. Must be my install then, still wondering why it has stopped working. I am exposing on a public domain, using the official docker image. Access to the API in a browser works from the same mobile.

**Comment by phantomate** [comment]
Hm. please try updating your tandoor instance, maybe that helps. I didn't change anything on the login part. I just fixed the meal plan issue that exisited due to the new tandoor version

**Comment by langerdennis** [comment]
I have already updated to the latest version, but thank you for checking. Will revert back to the PWA for now and hope I find the issue on my side at some point. Have just checked with the official instance again and it worked on 2nd try - got the user api error for this one as well, but only once. Weird behavior... Thank you for the great app anyways, really enjoy using it and hope it works for me again soon!

**Comment by langerdennis** [comment]
Found out my install was broken - working now! Sorry for the confusion

**Comment by m4tz3** [comment]
> Found out my install was broken - working now! Sorry for the confusion

Sorry, i was available the Last days. What was broken, how did you fix it?

**Comment by langerdennis** [comment]
I am running tandoor with sqlite and some database migration must have failed. Some column was missing and tandoor was throwing internal server errors. Unfortunately I had to restore from a backup and perform the update again, otherwise I would probably have needed to set up from scratch and reimport the recipes.

**Comment by langerdennis** [comment]
By the way, just found your [issue](https://github.com/TandoorRecipes/recipes/issues/2807) in the official Tandoor repo - this is exactly the problem I had with my instance earlier as well. Seems to be connected.

**Comment by phantomate** [comment]
closing this issue
