### ISSUE TITLE
Support Password Manager Autofill

### ISSUE THREAD

**Issue by FineFindus** [phantomate/Untare#59]
### Bug Summary

When trying to log in, the autofill option of my password manager (Bitwarden) does not appear. I'm using Android 10/EMUI with app version 1.2.0, downloaded from IzzyOnDroid.

### Reproduction Steps

1. Open the app
2. Try to fill in the password, notice how the autofill does not appear
3. Try to long tap to manually use autofill

### Expected Results

The autofill option should appear automatically, when trying to enter the username/password. Alternatively, the long press menu should also show the manual autofill option.

### Actual Results

Autofill showing up, or the manual option to force autofill appearing.
![Login field showing only the paste option](https://github.com/phantomate/Untare/assets/63370021/604ff451-6961-48c7-88a3-d6072b9e6347)

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by phantomate** [comment]
Hi @FineFindus, it works for me.

![Screenshot_20231222-092920](https://github.com/phantomate/Untare/assets/102902464/84eca160-6da9-488b-8111-a0fd720605e2)

Do you have the right settings and permissions in your bitwarden app?

**Comment by FineFindus** [comment]
Hmm, that's odd. The app should be setup right, as autofill works in all other apps.

**Comment by syphernl** [comment]
@phantomate Does it actually fill in the details in your case? For me it doesn't auto-fill the fields either.

**Comment by phantomate** [comment]
@syphernl You are right the auto-fill does not work
