### ISSUE TITLE
Allow meal plan without recipe

### ISSUE THREAD

**Issue by andersmmg** [phantomate/Untare#67]
### Your Request

Allow creating and viewing meal plans without a recipe attached for basic meal plans

### The Current State

Currently I get an API error when trying to create one, and if one exists when the app is open an error comes up on the bottom whenever data is loaded from the server.
"type 'Null' is not a subtype of type 'String' in type cast"

**Comment by phantomate** [comment]
Hi, this should already be possible. Just don't choose a recipe when adding a entry to the meal plan

**Comment by andersmmg** [comment]
That's what I did, I got the error I put in the issue

**Comment by phantomate** [comment]
Hi, do you still have the issue? What Tandoor version are you using?

**Comment by andersmmg** [comment]
I was using the latest at the time, and I don't think I've updated but it seems to work now! Hopefully it continues to work, maybe I can use it now
