### ISSUE TITLE
Password with ^ or # error

### ISSUE THREAD

**Issue by FL550** [phantomate/Untare#7]
First of all, thank you for the app. 

Unfortunately, when I try to login to my account with a password containing ^ and # characters, I get "user API error - wrong credentials". I double checked with the normal website, the password is working there.

**Comment by kgebert** [comment]
I've alao got login problems. Thanks for pointing to the workaround, @FL550!

**Comment by Szeraax** [comment]
I also had an issue logging in with password. Changed my password to `passphrases` and still not working :(

**Comment by gorgobacka** [comment]
Are you using the current version of Tandoor/Recipes: 1.4.4? I also couldn't log in but after upgrading the server it worked.

**Comment by Szeraax** [comment]
I was on 1.4.1. I saw someone else on 1.4.2. For both of us: Updating recipes to 1.4.4 fixed the issue and can login now.

**Comment by FL550** [comment]
Thanks for the help. Worked for me also.
