### ISSUE TITLE
Could not change space on iOs

### ISSUE THREAD

**Issue by fitus85** [phantomate/Untare#71]
### Bug Summary

If have configured 2 Spaces in Tandoor Web App. 
If i want change that from on space to another space only that space selected in the web app is shown. 
If space is switched in the web app. It is shown in settings > spaces, but not changed on the recipe page in the app. a app restart is needed, than the other changed space is opened directly. 

### Reproduction Steps

Jump to Settings > Spaces
Only one space is shown. 

### Expected Results

All spaces should be shown

### Actual Results

Could do nothing(uncheck or any other action) only back is possible. 

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by phantomate** [comment]
Hi @fitus85, there is currently no api endpoint for switching spaces. That's why the app just lists them
