### ISSUE TITLE
How to import I have api problem 

### ISSUE THREAD

**Issue by Mrunknow3** [phantomate/Untare#72]
![Screenshot_2024-03-19-19-20-31-756_unofficial.tandoor.recipes.jpg](https://github.com/phantomate/Untare/assets/154901963/6216f489-3c08-4c82-9ac2-0cc4986d1662)

**Comment by phantomate** [comment]
Hi, do you have this issue on all imports or just for a specific url?

**Comment by Mrunknow3** [comment]
I guess I have wrong url?

**Comment by phantomate** [comment]
Seems to be, not all urls are working
