### ISSUE TITLE
Show Properties

### ISSUE THREAD

**Issue by lukasspettel** [phantomate/Untare#73]
### Your Request

It would be amazing to have an option to display the properties defined in tandoor (nutritional value, etc) either in an optional third tab or somewhere better suited.

### The Current State

No option to display custom properties

**Comment by phantomate** [comment]
Hi, is this something that's already implemented in the web version? If so, please attach a screenshot

**Comment by lukasspettel** [comment]
Hi, thanks for getting back to me. It has already been implemented by defining custom properties and it's automatically calculating values for all ingredients once the values and unit conversions are set up.

Here is an example of how I've set them up (unfortunately in german):

![custom_properties](https://github.com/phantomate/Untare/assets/70133373/14345363-83dc-4b0e-9d44-f950dcacdb41)

**Comment by phantomate** [comment]
Hi, thanks for the screenshot. I added also some properties for testing and now I see the table from your screenshot. Never saw this before because I didn't add some properties.
It looks kinda easy to implement, so you will see this in the next release
