### ISSUE TITLE
Group by options in shopping list

### ISSUE THREAD

**Issue by rhyst** [phantomate/Untare#82]
### Your Request

I would like to be able to group by recipe or show now grouping in the shopping list. I currently don't use categories so I just see "Uncategorized" which is not useful. Thank you :)

**Comment by phantomate** [comment]
Hi, categories are exactly what you are looking for. Please use these for grouping.

**Comment by rhyst** [comment]
And the other half of my request was to not show the "Uncategorized" if there are no categories.
