### ISSUE TITLE
Swapping Spaces - iOS

### ISSUE THREAD

**Issue by Greg12312** [phantomate/Untare#83]
### Bug Summary

When clicking on "spaces" under miscellaneous settings only 1 shows up even though user belongs to multiple. Since other spaces don't show up, unable to swap to a different space. 

### Reproduction Steps

Click on settings and then spaces. 

### Expected Results

All spaces to show up and selectable to swap to active space. 

### Actual Results

Only the most recently created space shows up. 

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by phantomate** [comment]
Hi, switching spaces is currently not supported by the Tandoor API. Therefore I can't implement it.
