### ISSUE TITLE
Cannot import specific recipe

### ISSUE THREAD

**Issue by Salnex** [phantomate/Untare#84]
### Bug Summary

The following recipe fails to import. Stating "unexpected character( at character 1)

https://www.taste.com.au/recipes/tuna-mornay/67e496b4-32e6-45a5-a99e-d675f6960ad1

Other recipes from this website have previously import but it appears something has changed

### Reproduction Steps

Attempt to import a recipe from taste.com.au

The details will appear correctly

Trying to save the recipe fails citing the error anove

### Expected Results

The recipe to be imported

### Actual Results

The recipe was not imported

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by phantomate** [comment]
Hi, are you able to import it in the web version?
