### ISSUE TITLE
Properties are scaling incorrectly when changing the number of servings

### ISSUE THREAD

**Issue by ThomasHFWright** [phantomate/Untare#86]
### Bug Summary

Running the android app, when I change the number of servings the "total" column stays the same and the "per serving" column changes

### Reproduction Steps

Add a recipe with properties set up and change the number of servings

### Expected Results

The "per serving" column should stay the same and the "total" column should change

### Actual Results

The "total" column stays the same and the "per serving" column changes

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by phantomate** [comment]
Hi, this was fixed in the current release
