### ISSUE TITLE
Show recipe comments

### ISSUE THREAD

**Issue by hatty24** [phantomate/Untare#88]
### Your Request

It would be great to be able to read the comments that you can enter in the individual recipes in the Tandoor web version in the Untare app too.
We use this function to note important additional information about a recipe, for example.

**Comment by phantomate** [comment]
Hi, where should the comments be shown? I think I already show them on the recipe on the ingredients

**Comment by hatty24** [comment]
Hey, in the web version, the comments are at the bottom, under the preparation instructions.
In the app they are neither in the ingredients nor in the preparation instructions. At least I can't find it.
Here is an example, web version with commentary.
![IMG_0269](https://github.com/user-attachments/assets/110a4ef3-3e94-42e2-a2dc-fccefca3d614)

App view without.
![IMG_0268](https://github.com/user-attachments/assets/70dc15c8-353d-478d-a1a2-498c3942ba4c)

**Comment by phantomate** [comment]
Hi, I had a look at the API and it seems that this is currently not supported. At least I don't get this information via the API

**Comment by hatty24** [comment]
Pity.
Many thanks for your efforts.
