### ISSUE TITLE
Meals planned for tomorrow are shown today

### ISSUE THREAD

**Issue by veniplex** [phantomate/Untare#89]
### Bug Summary

The meal plan in the app shows the planned meal for the next day (tomorrow) today. This means that the app is one day ahead.

I am using Untare iOS v.1.3.0 and Tandoor Web v.1.5.18.
![image](https://github.com/user-attachments/assets/67d591ce-4470-4f21-80db-e4a684f297ad)
![image](https://github.com/user-attachments/assets/7334665c-0ec1-499a-a402-b33e6048aac0)

### Reproduction Steps

Plan a meal on the web app and open it in the iOS app.

### Expected Results

Shows meals planned for today.

### Actual Results

Show meals planned for tomorrow.

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by r00bit1984** [comment]
I have the same issue

**Comment by phantomate** [comment]
Hi, the error occurred due to the change in Tadoor. There the entries in the meal plan were changed from date to dateTime.
The fix is deployed soon on Android but will take some days for iOS. I need a new Iphone first, because of Apple things.

**Comment by r00bit1984** [comment]
Common Apple L
