### ISSUE TITLE
Ingredients link

### ISSUE THREAD

**Issue by Blue20210921** [phantomate/Untare#9]
In the app, linking recipes to ingredients does not work.
For example, I added the pita bread as an ingredient in a recipe, so when I press on it, I get to the recipe for the pita bread. This does not work in the app.

**Comment by phantomate** [comment]
Hi, thanks for your feature request! Could you please elaborate on that? And could you provide a screenshot on how it should like?

**Comment by eddiewebb** [comment]
Hey @phantomate , I'll pick this up.

You can turn certain recipes into a "food" (option on edit), and therefore use it in other recipes. When you do that the webapp/native UI will turn it into a link.  
<img width="463" alt="Screen Shot 2023-02-20 at 11 34 45 AM" src="https://user-images.githubusercontent.com/5262154/220160446-08b17305-5799-4c01-bb83-02e2b8aa4ac5.png">

I have attached a screenshot.
<img width="959" alt="Screen Shot 2023-02-20 at 11 32 50 AM" src="https://user-images.githubusercontent.com/5262154/220160460-124f5a8c-f5a1-4899-8cd1-d447a2300133.png">

**Comment by eddiewebb** [comment]
The underlying data is simply presence of 'recipe' on a food.

<img width="905" alt="Screen Shot 2023-02-20 at 11 37 29 AM" src="https://user-images.githubusercontent.com/5262154/220161011-06b8f16f-605f-441a-ae8d-6191c820bbe8.png">

**Comment by phantomate** [comment]
Hi @eddiewebb thank you  for the clarification. I try to inlcude this in the next release

**Comment by phantomate** [comment]
Unfortunately, I have lost sight of this a little. I try to include this in the next release

**Comment by phantomate** [comment]
Added in newest release (1.3.0)
