### ISSUE TITLE
Cannot set name to recipe (Expects a number < 128)

### ISSUE THREAD

**Issue by Piztou** [phantomate/Untare#91]
### Bug Summary

I cannot edit or create a new recipe without having to set the name to a number.

Any int or decimal number seems to currently work as long as it's below 128 (ex , `-325`, `129e-1`,...).  But not any extra chars.

I'm guessing the system checks the max value instead of the max size of the input.

### Reproduction Steps

On Android 14, using the latest version on the Play Store, create a new recipe, or edit any existing one.

### Expected Results

Being able to keep/set a proper name for the recipe, not a number

### Actual Results

The Name fields gets highlighted in red with the message `Value must be less than or equal to 128`, which prevents from saving the changes

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by phantomate** [comment]
Hi, you are right, I updated the form widget in the last version and it seems that is broke something. I'm currently not in town so it will take some days for me to fix it.
