### ISSUE TITLE
Scrolling ingredients and directions by pressing volume hardware buttons

### ISSUE THREAD

**Issue by serrq** [phantomate/Untare#95]
![1000116093](https://github.com/user-attachments/assets/0f084f5e-87fb-489f-b14b-da8b3b0b653e)

**Comment by phantomate** [comment]
Hi, hm this does not make sense to me. Why not just swipe left and right?

**Comment by phantomate** [comment]
But even if you could use the volume buttons your mobile phone would get dirty
